# Generated by Django 5.2 on 2025-04-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
